// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpe176iYeHgj8TecImp5IhQpOzTMqj-mA',
    appId: '1:1012485903478:web:c1a0bf677b60f1466ebb57',
    messagingSenderId: '1012485903478',
    projectId: 'habittracker-1b497',
    authDomain: 'habittracker-1b497.firebaseapp.com',
    storageBucket: 'habittracker-1b497.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuR_Tn_j4EgAzS5662_co6rnKiSkihzb4',
    appId: '1:1012485903478:android:06ead8001f70033b6ebb57',
    messagingSenderId: '1012485903478',
    projectId: 'habittracker-1b497',
    storageBucket: 'habittracker-1b497.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyj73W7fjLlg9V4J52puF9ci-k20qG-3M',
    appId: '1:1012485903478:ios:916add5b8e8bbd0f6ebb57',
    messagingSenderId: '1012485903478',
    projectId: 'habittracker-1b497',
    storageBucket: 'habittracker-1b497.appspot.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyj73W7fjLlg9V4J52puF9ci-k20qG-3M',
    appId: '1:1012485903478:ios:916add5b8e8bbd0f6ebb57',
    messagingSenderId: '1012485903478',
    projectId: 'habittracker-1b497',
    storageBucket: 'habittracker-1b497.appspot.com',
    iosBundleId: 'com.example.habitTracker',
  );
}
